name: Upload Artifact

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on PR to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload HTML Artifact
      uses: actions/upload-artifact@v2  # Updated to v2
      with:
        name: html-file
        path: index.html  # The path to your HTML file
