name: Test Self-hosted Runner

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: [self-hosted, linux]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run HTTP Server in the Background
        run: |
          nohup python3 -m http.server 8080 &
          echo "HTTP server started in the background"
      
      - name: Wait for the server to run for a while
        run: sleep 30  # Sleep for 30 seconds to let the server run
      
      - name: Additional Steps
        run: |
          echo "Additional steps after HTTP server runs"
